# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 2.2.13"

Vagrant.configure("2") do |config|

   config.vm.synced_folder ".", "/vagrant", disabled: true

   config.ssh.insert_key = false

   config.vm.define "js-code" do |code|
      code.vm.box = "launchquickly/focal-desktop64"
      code.vm.box_version = "0.0.6"

      code.vm.hostname = "js-code"

      code.vm.network :private_network, ip: "10.205.0.20"

      code.vm.provider "virtualbox" do |vb|
         vb.gui = true
         vb.memory = 4096
         vb.cpus = 2
         vb.customize ["modifyvm", :id, "--vram", "128"]
         vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
      end

      # install nodejs and npm
      # install vscode
      code.vm.provision "shell", inline: <<-SHELL
         nodejs_version=v14.15.1
         nodejs_distro=linux-x64

         wget https://nodejs.org/dist/${nodejs_version}/node-${nodejs_version}-${nodejs_distro}.tar.xz

         mkdir -p /usr/local/lib/nodejs
         tar -xJvf node-${nodejs_version}-${nodejs_distro}.tar.xz -C /usr/local/lib/nodejs 

         rm ./node-${nodejs_version}-${nodejs_distro}.tar.xz

         snap install code --classic

         # VS code needs the number of file handles to be increased to manage npm modules
         echo "" >> /etc/sysctl.conf
         echo "fs.inotify.max_user_watches=524288" >> /etc/sysctl.conf
         sysctl -p
         # TODO investigate whether these should instead be excluded: 
         # https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc
      SHELL

      # configure nodejs and npm
      # checkout javascript repository as vagrant user
      code.vm.provision "shell", privileged: false, inline: <<-SHELL
         nodejs_version=v14.15.1
         nodejs_distro=linux-x64

         echo "" >> ~/.profile
         echo "export PATH=/usr/local/lib/nodejs/node-${nodejs_version}-${nodejs_distro}/bin:$PATH" >> ~/.profile
         source ~/.profile

         # Configure npm directory to avoid permissions issues for global installs
         mkdir ~/.npm-global
         npm config set prefix '~/.npm-global'
         echo "" >> ~/.profile
         echo "export PATH=~/.npm-global/bin:$PATH" >> ~/.profile
         source ~/.profile

         git clone https://github.com/launchquickly/javascript.git
         cd javascript
         # change repository remote access from https to ssh
         git remote set-url origin git@github.com:launchquickly/javascript.git
      SHELL
   end
end
